name: flutter_minesweeper
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_localizations: # 多言語ライブラリの本体
    sdk: flutter
  intl: ^0.17.0 # 多言語やフォーマッタなどの関連ライブラリ

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true
  uses-material-design: true
